$background = rgb(051117)
$foreground = rgb(c7e5eb)
$color0 = rgb(051117)
$color1 = rgb(387089)
$color2 = rgb(457A93)
$color3 = rgb(5691AC)
$color4 = rgb(69AECE)
$color5 = rgb(6FB6D4)
$color6 = rgb(86BAD2)
$color7 = rgb(c7e5eb)
